spring.application.name=main-api
server.port=8080

# Banco de dados
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jackson.default-property-inclusion=always
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
management.endpoints.web.exposure.include=mappings

#JPA
jwt.secret=${JWT_SECRET}

#CLOUD-AMQP (RABBIT-MQ)
spring.rabbitmq.host=${AMQP_HOST}
spring.rabbitmq.port=${AMQP_PORT}
spring.rabbitmq.virtual-host=${AMQP_VIRTUAL_HOST}
spring.rabbitmq.username=${AMQP_USERNAME}
spring.rabbitmq.password=${AMQP_PASSWORD}
fila-registro-ocorrencia=estatisticas-queue